# Generated by Django 2.1.4 on 2019-01-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcard',
            options={'ordering': ['-id'], 'verbose_name': '个人卡片', 'verbose_name_plural': '个人卡片'},
        ),
    ]
