# Generated by Django 2.1.4 on 2018-12-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181223_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homebanner',
            old_name='iamge',
            new_name='image',
        ),
    ]
