# Generated by Django 2.1.4 on 2018-12-23 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181223_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, verbose_name='创造时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(default='博主', max_length=100, verbose_name='作者')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('response_count', models.IntegerField(default='5', verbose_name='点击数')),
                ('blog_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='博客链接')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '博客类型',
                'verbose_name_plural': '博客类型',
            },
        ),
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(verbose_name='文本1')),
                ('text2', models.TextField(verbose_name='文本2')),
                ('text3', models.TextField(verbose_name='文本3')),
                ('csdn_url', models.CharField(max_length=20, verbose_name='CSDN博客地址')),
                ('image', models.ImageField(upload_to='image/%Y/%m', verbose_name='个性图片')),
            ],
            options={
                'verbose_name': '个人介绍',
                'verbose_name_plural': '个人介绍',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BlogType', verbose_name='博客类型'),
        ),
    ]
