# Generated by Django 2.1.4 on 2019-01-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190102_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolgbanner',
            options={'verbose_name': '博客轮播图', 'verbose_name_plural': '博客轮播图'},
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
        migrations.AlterModelOptions(
            name='personcard',
            options={'verbose_name': '个人卡片', 'verbose_name_plural': '个人卡片'},
        ),
    ]
