# Generated by Django 2.1.4 on 2019-01-02 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190102_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_url',
            field=models.CharField(blank=True, max_length=50, verbose_name='博客链接'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(blank=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='blogtype',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='bolgbanner',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_banner/%Y/%m', verbose_name='博客轮播图'),
        ),
        migrations.AlterField(
            model_name='bolgbanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='personcard',
            name='card_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='卡片名字'),
        ),
        migrations.AlterField(
            model_name='personcard',
            name='card_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='卡片说明'),
        ),
        migrations.AlterField(
            model_name='personcard',
            name='card_url',
            field=models.CharField(blank=True, max_length=150, verbose_name='卡片地址'),
        ),
        migrations.AlterField(
            model_name='personcard',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='text1',
            field=models.TextField(blank=True, verbose_name='文本1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='text2',
            field=models.TextField(blank=True, verbose_name='文本2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='text3',
            field=models.TextField(blank=True, verbose_name='文本3'),
        ),
    ]
