# Generated by Django 2.1.4 on 2018-12-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181223_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(verbose_name='标题'),
        ),
    ]
