# Generated by Django 2.1.4 on 2018-12-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181223_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homeblogimage/%Y/%m', verbose_name='首页博客缩图'),
        ),
    ]
