# Generated by Django 2.1.4 on 2018-12-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='访问地址'),
        ),
    ]
