# Generated by Django 2.1.4 on 2019-01-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190107_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间'),
        ),
    ]
