# Generated by Django 2.1.4 on 2018-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181227_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='click_number',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='response_count',
            field=models.IntegerField(default=0, verbose_name='回复数'),
        ),
    ]
