# Generated by Django 2.1.4 on 2018-12-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181229_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blog_type/%Y/%m', verbose_name='分类插图'),
        ),
        migrations.AlterField(
            model_name='myself',
            name='image',
            field=models.ImageField(upload_to='myself/%Y/%m', verbose_name='个性图片'),
        ),
    ]
